### ISSUE TITLE
undefined symbol dspr_

### ISSUE THREAD

**Issue by rameshsrinivasanuci** [openmeeg/openmeeg#243] opened 2017-10-03 08:18 UTC
Hello - 
I downloaded the latest version 2.4.0.0 of OpenMEEG.  I have previously used an earlier version, but was very interested in your new non-nested capabilities Maureen informed me. I am running this on Ubuntu 16.04 

I am running into the same error when using either my meshes or with your sample data set given in 
openmeeg_sample_data-master.zip in the  data/model folder.   I am able to assemble using 

om_assemble -HeadMat head_model.geom head_model.cond head_model_hm_v4.mat 

But when I try to use om_minverser as 

om_minverser head_model_hm_v4.mat head_model_hm_v4_inv.mat 

I get the following error almost immediately

| ------ om_minverser
| head_model_hm_v4.mat
| head_model_hm_v4_inv.mat
| -----------------------
om_minverser: symbol lookup error: om_minverser: undefined symbol: dspr_

Any help would be appreciated. 
ramesh

**Comment by agramfort** [comment] 2017-10-03 08:27
@rameshsrinivasanuci what precompiled binaries did you install?

**Comment by rameshsrinivasanuci** [comment] 2017-10-03 13:09
Hi - Thanks for the quick response. 
OpenMEEG-2.4.0.0-Linux-LAPACK-OpenMP.tar.gz.  
ramesh

**Comment by agramfort** [comment] 2017-10-03 19:05
honestly I don't know. You might want to try to compile yourself or just
wait a few weeks
so we can fix the packaging problem on linux.

**Comment by mclerc** [comment] 2017-10-10 08:45
Dear Ramesh, 
Do you have the possibility to compile the code ? 
This may be the quickest fix to your problem. 
Thank you for reporting the issue which we will endeavour to tackle. 
Best regards, 

Maureen 

----- Mail original -----

| honestly I don't know. You might want to try to compile yourself or just
| wait a few weeks
| so we can fix the packaging problem on linux.

| —
| You are receiving this because you are subscribed to this thread.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by rameshsrinivasanuci** [comment] 2017-10-10 15:14
Hi Maureen 
I have not yet tried compiling. 
Do you know if it works seamlessly on windows?  Is that the more robustly tested environment?
Thanks
Ramesh


Sent from my HTC on T-Mobile 4G LTE

----- Reply message -----

**Comment by papadop** [comment] 2017-10-10 17:36
On 10/10/2017 05:14 PM, rameshsrinivasanuci wrote:
> Hi Maureen
> I have not yet tried compiling.
> Do you know if it works seamlessly on windows? Is that the more robustly
> tested environment?
> Thanks
> Ramesh

The problem is that linux has quite a lot variability with many
distributions and many versions.... Thus there is a good chance that the
windows version works better in you case (which is funny given that
OpenMEEG is mstly developped on linux computers).

That being said, I must say that I do not understand the problem that
you encounter as the dspr routine is part of the blaslapack interface
for quite some time and seems quite fundamental.... All the more that we
normally ship all the necessary libraries with openmeeg.

I have just followed lightly the thread. Did someone asked you to do:
ldd of the command you use (ldd command_full_path), and give us the
result ?? Because we had a conversation with Alex and Maureen tonight
and your problem seems very weird...

	Theo.

**Comment by rameshsrinivasanuci** [comment] 2017-10-19 19:33
Hi Theo -

Could I inquire from you the linux distribution you use for testing 
2.4.00.  I had no luck with compiling, it claimed a problem with the 
make file.  I can send that to you if you want.

Interestingly, we had one computer where we were able to get 2.3.99 
binaries to work.  Its running Ubuntu 14.04.2.  All the failures were on 
16.10.

My main main motive to switch to OpenMEEG from FEM models is the 
possibility of non-nested meshes for Lesioned brains.  So, it might be 
best if I get 2.4.00 to run.

ramesh

**Comment by rameshsrinivasanuci** [comment] 2017-10-20 04:55
Hi Theo, Alexander, Maureen Thank you for all your help.  I now have 
functioning 2.4.0 using Ubuntu 16.04 with kernel 4.4.0-96-generic.

It still remains the case that our CentOS servers don't work, but I 
think this is because CentOS tends to be "behind".

I look forward to working with Open MEEG.  Thank you for making such a 
useful tool available to all of us.

ramesh

**Comment by agramfort** [comment] 2018-08-24 11:39
New binaries should work. Closing.

**Closed by agramfort** 2018-08-24 11:39 UTC
