### ISSUE TITLE
tests failing on Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [openmeeg/openmeeg#79] opened 2015-12-05 16:02 UTC
```
The following tests FAILED:
    123 - DipGainInternalPot-HeadNNc1 (SEGFAULT)
    132 - InternalPot-dipoles-HeadNNc1 (OTHER_FAULT)
    152 - DipGainInternalPot-Head2 (SEGFAULT)
    161 - InternalPot-dipoles-Head2 (OTHER_FAULT)
    248 - cmp-EEGinternal-dip-Head2-dip1 (Failed)
    250 - cmp-EEGinternal-dip-Head2-dip2 (Failed)
    252 - cmp-EEGinternal-dip-Head2-dip3 (Failed)
    254 - cmp-EEGinternal-dip-Head2-dip4 (Failed)
    256 - cmp-EEGinternal-dip-Head2-dip5 (Failed)
```

regarding Head2-dipX tests I dont see generated file `build/tests/Head2-dip-internal.est_eeg`
and for others it crashes somewhere in libatlas.so (`OpenMEEG::Matrix::operator*`)

**Comment by agramfort** [comment] 2015-12-07 08:49
@papadop do you plan to have a look?

**Comment by papadop** [comment] 2015-12-07 08:55
Yep. Fedora is easy for me.... Maybe not today but very soon...

**Comment by papadop** [comment] 2015-12-07 17:56
Which version of fedora are you using. For me it works well on fedora 21.... I suspect you use a newer version I have not access to yet... The problem is probably the first crash. The file Head2-dip-internal.est_eeg is generated by DipGainInternalPot-Head2 or InternalPot-dipoles-Head2. The second fails because of the first which probably fails similarly to DipGainInternalPot-HeadNNc1. It is somewhat strange that you do not get errors fot HeadNNc1 cmp-* tests

So which version of fedora do you use. And do you use any OpenMEEG options (I see after that you asked for vtk support).

Thank's for the report. I hope to be able to analyze what happens more thoroughly soon.

**Comment by ignatenkobrain** [comment] 2015-12-07 21:36
As usual, rawhide (24).

**Comment by agramfort** [comment] 2017-06-08 13:52
I think this is fixed now.

**Closed by agramfort** 2017-06-08 13:52 UTC
